### ISSUE TITLE
how do i fix this?

### ISSUE THREAD

**Issue by amneetiscool1234** [Friends-of-Monika/mas-presence#27]
![image](https://user-images.githubusercontent.com/117772447/200657580-3ed656ef-4d54-4db2-b92c-172fe01cf560.png)

![image](https://user-images.githubusercontent.com/117772447/200657751-262c4bde-3fc0-455d-919c-205b589dc2b4.png)

**Comment by dreamscached** [comment]
Please check again how you installed it and follow the install guide. You have installed it wrong. Delete all the files you copied into `game`.

Also, do not download this submod using 'download code' button you see; use [releases page](https://github.com/Friends-of-Monika/mas-presence/releases/tag/0.4.0).

**Comment by dreamscached** [comment]
Closing as stale.
